version: '3'
services:
  app:
    container_name: docker-node-mongo-AP
    restart: always
    build: .
    ports:
      - '8091:8091'
    links:
      - mongo
    volumes: ['./:/usr/src/app']

  mongo:
    container_name: mongo-AP
    image: mongo
    ports:
      - '27017:27017'
